# Generated by Django 4.2 on 2023-05-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encadrents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupes',
            fields=[
                ('id_group', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('id_encadreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encadrents.encadrents')),
            ],
        ),
    ]
