# Generated by Django 4.2 on 2023-05-10 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0001_initial'),
        ('groupes', '0001_initial'),
        ('etudients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='etudient',
            name='prenome',
        ),
        migrations.AddField(
            model_name='etudient',
            name='id_dep',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='departements.departements'),
        ),
        migrations.AddField(
            model_name='etudient',
            name='id_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='groupes.groupes'),
        ),
    ]
